server:
  port: 9091
  forward-headers-strategy: framework

logging:
  level:
    root: ERROR
    '[org.springframework.web]': ERROR
    '[br.com.k3t.api.oauth]': TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: https://{DOMAIN}/                           
          issuer-uri: http://localhost:8080/realms/demo

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
    
  oAuthFlow:
    authorizationUrl: http://localhost:8080/realms/demo/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/realms/demo/protocol/openid-connect/token